# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [77]:
import numpy as np
array = np.arange(0,10)
print("1D Array : ",array)
print("2D Array : ",array.reshape(2,-1))

1D Array :  [0 1 2 3 4 5 6 7 8 9]
2D Array :  [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [50]:
array_2D = array.reshape(2,-1)
array_2 = np.ones(10).astype(np.int32)
array_2 = array_2.reshape(2,-1)
np.vstack((array_2D,array_2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [51]:
np.hstack((array_2D,array_2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [93]:
arrary_of_arrays = array_2D.reshape(5,2,-1)
print("array of arrays \n",arrary_of_arrays )
arrays_flattened = arrary_of_arrays.flatten()
print("array of arrays flattened \n",arrays_flattened)

array of arrays 
 [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]
array of arrays flattened 
 [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [90]:
array_of_higher_dimension = np.arange(15).reshape(3,5)
print("converting an array of higher dimension in and array of one dimension \n",array_of_higher_dimension.reshape(-1))

converting an array of higher dimension in and array of one dimension 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [95]:
array_of_one_dimension = np.arange(15)
print("array of one dimention into array of higher dimension",array_of_higher_dimension.reshape(3,5))

array of one dimention into array of higher dimension [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [110]:
array_5_x_5 = np.arange(25).reshape((5,5))
np.square(array_5_x_5)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [111]:
array_5_x_6 = np.arange(30).reshape(5,6)
np.mean(array_5_x_6)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [112]:
array_5_x_6.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [114]:
np.median(array_5_x_6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [118]:
array_5_x_6.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [123]:
array_4_x_4 = np.arange(16).reshape(4,4)
print(array_4_x_4,np.diagonal(array_4_x_4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] [ 0  5 10 15]


## Question:13

### Find the determinant of the previous array in Q12?

In [127]:
np.linalg.det(array_4_x_4)
np.linalg.det(array_4_x_4)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [138]:
arr_p = np.arange(100)
print("5th percentile: ", np.percentile(arr_p,5) )
print("85th percentile: ", np.percentile(arr_p,85) )

5th percentile:  4.95
85th percentile:  84.14999999999999


## Question:15

### How to find if a given array has any null values?

In [139]:
np.isnan(array_4_x_4)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])